"""Top-down map of the proof. Writes ../proof-map.pdf.

Usage: python3 proof_map.py [AUX]

AUX is the aux file of a build of the paper (default: paper/build/main.aux of
this checkout, as written by the build command in paper/README.md). The
statement and section numbers in the figure are read from it.
"""
from pathlib import Path
import sys
HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
OUT = HERE.parent
AUX = Path(sys.argv[1]).expanduser().resolve() if len(sys.argv) > 1 else ROOT / 'paper' / 'build' / 'main.aux'
# Top-down proof map. Each box: the name of a step on top, under it the result
# that proves the step (or the section, where no single result does), then its
# content. The kinds (Lemma, Section, ...) are written here, as in the paper's
# own cross-references, and the numbers are read from AUX through the labels,
# so that after a renumbering the figure is regenerated by one command.
# Ink only, straight arrows, no text outside the boxes.
import numpy as np
from paperstyle import *
setup()
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, PathPatch
from matplotlib.path import Path as MPath

W = 5.8
FS_H, FS_B = 7.9, 8.6          # header and body sizes, and the result line has the header size
BW, BWL = 1.66, 1.57            # box width; the left column is narrower to leave room for its lane
PADT, PADB, GAP_HB = 0.068, 0.075, 0.05
LW_BOX, LW_FINAL, LW_RULE, LW_ARR = 0.7, 1.4, 0.4, 0.75
ROWGAP = 0.21
SETUPGAP = 0.16                 # no arrows leave the setup, so its gap is smaller
MARG = 0.04                     # white space above and below
LANE = 0.12                     # distance from a box edge to a lane
XL, XM, XR = 0.995, 2.855, 4.76    # equal gaps; a lane on each side, the same margin outside each lane

# (key, column x, row, header, results, body), with results as (kind, label) pairs
PROOF_T11 = [('Proof of Theorem', 'thm:radial-profile')]    # steps inside the proof of the radial law, in Section 6
SPEC = [
 ('G', XM, 0, 'Setup', PROOF_T11, r'$f_n(z)=\epsilon_0+\epsilon_1 z+\cdots+\epsilon_n z^n$' '\n' r'blocks $N=j^8\leq n<(j+1)^8$' '\n' r'fixed $x$ and $K\geq |x|+2$, band $N^{-65/64}$'),
 ('P', XL, 1, 'Variance profile', [('Proposition', 'prop:profiles'), ('Lemma', 'lem:profile-rate')], r'$\log\sigma_N(1+x/N)-\frac{1}{2}\log N$' '\n' r"$\to F(x)$ with $F'=\Phi$"),
 ('A', XM, 1, 'Angular logarithm', [('Theorem', 'thm:sign-logarithms')], r'$J_N(r)=\log\sigma_N(r)-\gamma/2$' '\n' r'$+\,o(1)$ for $|r-1|\leq K/N$'),
 ('C', XR, 1, 'Derivative and tail bounds', [('Lemma', 'lem:second-derivative'), ('Lemma', 'lem:tails')], 'Hoeffding on a mesh' '\n' r'$|f_N^{\prime\prime}|\leq C(K)N^{5/2}\sqrt{\log N}$' '\n' r'$|f_n-f_N|<a$ on the block'),
 ('B', XL, 2, 'Small derivatives', [('Lemma', 'lem:small-derivatives')], 'second moment on a mesh' '\n' r'$\#\{|f_N^{\prime}(\alpha)|<N^{3/2-1/64}\}$' '\n' r'$\leq C(K)N^{15/16}\log N$'),
 ('J', XM, 2, 'Annular mass', [('Corollary', 'cor:radial-probability'), ('Lemma', 'lem:local-radial-secant')], 'Jensen secants give' '\n' r'$\#\{||\alpha|-1|>K/N\}$' '\n' r'$\leq N\,(2\log 2/K+o(1))$' '\n' r'and $\nu_N(1+y/N)\sim N\Phi(y)$'),
 ('L', XR, 2, 'Disjoint disks', [('Lemma', 'lem:isolation-interface')], r'if $|f_N^{\prime}(\alpha)|\geq d_0$, then $\alpha$' '\n' r'is alone in the disk $D$' '\n' r'of radius $2a/d_0$ about it,' '\n' r'disjoint, $|f_N|>a$ on $\partial D$'),
 ('U', XL, 3, 'Unselected roots', PROOF_T11, r'outside $||z|-1|\leq K/N$' '\n' r'or with small $|f_N^{\prime}|$' '\n' r'$U_N\leq N\,(2\log 2/K+o(1))$'),
 ('Cn', XM, 3, 'Boundary disks', PROOF_T11, r'$c_N=o(N)$ disks meet' '\n' r'the target circles, as' '\n' r'$2a/d_0<N^{-65/64}$'),
 ('M', XR, 3, 'Root matching', [('Theorem', 'thm:T4')], "Rouché's theorem gives" '\n' r'$|\nu_n(1+x/n)-\nu_N(1+x/N)|$' '\n' r'$\leq c_N+U_N+m_j$'),
 ('RT', XL, 4, 'Logarithmic rate', [('Theorem', 'thm:log-rate')], r'take $K_N\approx\log N/128$' '\n' r'$(\log n)\,|\nu_n(1)/n-1/2|$' '\n' r'$\leq 128+o(1)$'),
 ('BC', XM, 4, 'Borel–Cantelli', PROOF_T11, r'summable over $N=j^8$, a.s.' '\n' r'$\limsup|\nu_n(1+x/n)/n$' '\n' r'$-\,\Phi(x)|\leq 2\log 2/K$'),
 ('X', XR, 4, 'Hypotheses (H1)–(H5)', [('Proposition', 'prop:coefficient-transfer')], 'logarithmic, local-count,' '\n' 'derivative and tail bounds' '\n' 'for other distributions'),
 ('T8', XL, 5, 'Radial law', [('Theorem', 'thm:radial-profile')], r'as $K\to\infty$, almost surely' '\n' r'$\nu_n(1+x/n)/n\to\Phi(x)$' '\n' r'uniformly on compact sets'),
 ('T6', XM, 5, 'Unit-disk law', [('Corollary', 'thm:stronglaw')], r'Erdős #522, the case $x=0$' '\n' r'$\nu_n(1)/n\to 1/2$' '\n' 'almost surely'),
 ('CM', XR, 5, 'Other distributions', [('Theorem', 'thm:radial-profile'), ('Corollary', 'thm:stronglaw')], 'the same proof under' '\n' '(H1)–(H5): Steinhaus,' '\n' 'Gaussian, bounded' '\n' 'symmetric coefficients'),
]
FINAL = {'T8', 'T6', 'CM'}      # the three results, drawn alike

def groups(s):
    """The top-level brace groups of s, skipping escaped characters."""
    out, depth, i = [], 0, 0
    while i < len(s):
        c = s[i]
        if c == '\\': i += 1
        elif c == '{':
            if depth == 0: start = i + 1
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0: out.append(s[start:i])
        i += 1
    return out
def aux_numbers(path, labels):
    """Number of each label in the aux file. Stops if a label is missing, repeated or of the wrong kind."""
    if not path.is_file(): sys.exit(f'proof_map.py: no aux file {path}. Build the paper or pass its aux file.')
    found = {}
    for line in path.read_text(errors='replace').splitlines():
        if not line.startswith('\\newlabel{'): continue
        g = groups(line[len('\\newlabel'):])
        if len(g) == 2 and g[0] in labels: found.setdefault(g[0], set()).add(tuple(groups(g[1])))
    nums = {}
    for lab, kind in sorted(labels.items()):
        if lab not in found: sys.exit(f'proof_map.py: label {lab} is missing from {path}')
        if len(found[lab]) > 1: sys.exit(f'proof_map.py: label {lab} is defined more than once in {path}')
        f = next(iter(found[lab])); num = f[0]
        if not num or not all(c.isalnum() or c == '.' for c in num):
            sys.exit(f'proof_map.py: label {lab} has the number {num!r} in {path}')
        anchor = f[3].split('.')[0] if len(f) > 3 else None      # hyperref anchor, e.g. theorem.1.2
        want = ('section', 'subsection', 'subsubsection', 'appendix') if kind == 'Section' else ('theorem',)
        if anchor is not None and anchor not in want:
            sys.exit(f'proof_map.py: label {lab} is a {anchor}, not a {kind}, in {path}')
        nums[lab] = num
    return nums
NUM = aux_numbers(AUX, {lab: kind for *_, res, _ in SPEC for kind, lab in res})
def cite(res):
    return ', '.join(f'{kind} {NUM[lab]}' for kind, lab in res)
SPEC = [(k, x, r, hd, cite(res), bd) for k, x, r, hd, res, bd in SPEC]
print(AUX)
for k, x, r, hd, rs, bd in SPEC: print(f'  {hd}: {rs}')

# pass 1, measure
fig0 = plt.figure(figsize=(W, 8)); ax0 = fig0.add_axes([0, 0, 1, 1]); ax0.set_xlim(0, W); ax0.set_ylim(0, 8)
R0 = fig0.canvas.get_renderer(); inv0 = ax0.transData.inverted()
def hgt(s, fs, **kw):
    t = ax0.text(0, 4, s, fontsize=fs, linespacing=1.36, **kw)
    bb = t.get_window_extent(R0).transformed(inv0); t.remove(); return bb.height, bb.width
meas = {}
for k, x, r, hd, rs, bd in SPEC:
    hh, hw = hgt(hd, FS_H, weight='bold'); rh, rw = hgt(rs, FS_H); bh, bw = hgt(bd, FS_B)
    meas[k] = (hh, bh, max(hw, rw, bw))
    if max(hw, rw, bw) + 0.12 > (2.3 if k == 'G' else BWL if x == XL else BW): print('text wider than its box', k)
plt.close(fig0)
nrow = 1 + max(s[2] for s in SPEC)
BASE, REF, RULE = 0.148, 0.278, 0.326   # header and result baselines and the rule, measured from the box top
rowh = [max(RULE + GAP_HB + meas[k][1] + PADB for k, x, r, *_ in SPEC if r == i) for i in range(nrow)]
H = MARG + sum(rowh) + SETUPGAP + ROWGAP * (nrow - 2) + MARG
tops = []; y = H - MARG
for i in range(nrow):
    tops.append(y); y -= rowh[i] + (SETUPGAP if i == 0 else ROWGAP)
print(f'height {H:.3f} in')

fig = plt.figure(figsize=(W, H)); ax = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, W); ax.set_ylim(0, H); ax.axis('off')
N = {}
for k, x, r, hd, rs, bd in SPEC:
    top = tops[r]; h = rowh[r]; bot = top - h
    w = 2.3 if k == 'G' else (BWL if x == XL else BW)
    fin = k in FINAL
    ax.add_patch(FancyBboxPatch((x - w / 2, bot), w, h, boxstyle='square,pad=0', fc='white',
                                ec=INK, lw=LW_FINAL if fin else LW_BOX, zorder=3))
    hh, bh, _ = meas[k]
    ax.text(x, top - BASE, hd, ha='center', va='baseline', fontsize=FS_H, weight='bold', color=INK, zorder=4)
    ax.text(x, top - REF, rs, ha='center', va='baseline', fontsize=FS_H, color=INK, zorder=4)
    yr = top - RULE
    ax.plot([x - w / 2 + 0.07, x + w / 2 - 0.07], [yr, yr], color=INK, lw=LW_RULE, zorder=4, solid_capstyle='butt')
    # body centred in the remaining space
    ymid = (yr + bot) / 2
    ax.text(x, ymid, bd, ha='center', va='center', fontsize=FS_B, color=INK, multialignment='center', linespacing=1.36, zorder=4)
    N[k] = dict(x=x, y=bot + h / 2, l=x - w / 2, r=x + w / 2, b=bot, t=top)

def arrow(p0, p1):
    ax.add_patch(FancyArrowPatch(p0, p1, arrowstyle='-|>,head_length=4.4,head_width=2.0', mutation_scale=1.0,
                 lw=LW_ARR, color=INK, shrinkA=0, shrinkB=0.7, zorder=2, joinstyle='miter', capstyle='butt'))
def down(a, b, fa=0.0, fb=0.0):
    A, B = N[a], N[b]; arrow((A['x'] + fa, A['b']), (B['x'] + fb, B['t']))

# No arrows leave the setup: it fixes the notation of every box.
down('P', 'J', fa=0.45, fb=-0.45)
down('A', 'J')
down('C', 'L')
down('B', 'U')
down('J', 'U', fa=-0.45, fb=0.45)
down('J', 'Cn')
down('L', 'Cn', fa=-0.45, fb=0.45)
down('L', 'M')
def lane(a, b, right):
    """From the side of box a along an outer lane to the same side of box b."""
    A, B = N[a], N[b]; rr = 0.07
    e0, e1 = (A['r'], B['r']) if right else (A['l'], B['l'])
    xl = e0 + LANE if right else e0 - LANE
    sx = 1 if right else -1
    P = [(e0, A['y']), (xl - sx * rr, A['y']), (xl, A['y']), (xl, A['y'] - rr), (xl, B['y'] + rr), (xl, B['y']), (xl - sx * rr, B['y'])]
    codes = [MPath.MOVETO, MPath.LINETO, MPath.CURVE3, MPath.CURVE3, MPath.LINETO, MPath.CURVE3, MPath.CURVE3]
    ax.add_patch(PathPatch(MPath(P, codes), fc='none', ec=INK, lw=LW_ARR, zorder=2, capstyle='butt'))
    arrow(P[-1], (e1, B['y']))
lane('C', 'M', right=True)      # around the disjoint disks
lane('P', 'T8', right=False)    # the profile is also the limit in the radial law
down('U', 'BC', fa=0.45, fb=-0.45)
down('Cn', 'BC')
down('M', 'BC', fa=-0.45, fb=0.45)
down('BC', 'T8', fa=-0.45, fb=0.45)
down('BC', 'CM', fa=0.45, fb=-0.45)
down('X', 'CM')
def side(a, b):
    A, B = N[a], N[b]
    if B['x'] > A['x']: arrow((A['r'], A['y']), (B['l'], B['y']))
    else: arrow((A['l'], A['y']), (B['r'], B['y']))
side('BC', 'RT')
side('T8', 'T6')                # the unit-disk law is the case x=0

fig.savefig(OUT / 'proof-map.pdf')
